import type { Locale } from "@/i18n/locale";
import { translate } from "@/i18n/messages";
import type { MapPoint } from "@/domain/map/schema";
/** Decode only labels generated by our adapters; source IDs and raw fields stay intact. */
export function mapPointLabel(point: MapPoint, locale: Locale): string {
  const tower = /^(上路|中路|下路|左侧|右侧) ([1-4])级塔$/u.exec(point.label);
  if (tower)
    return translate(locale, "{lane} {tier}级塔", {
      lane: translate(locale, tower[1]),
      tier: tower[2],
    });
  const tier = /^([1-4]) 级防御塔$/u.exec(point.label);
  if (tier) return translate(locale, "{tier} 级防御塔", { tier: tier[1] });
  return translate(locale, point.label);
}
export function unitVariant(value: string, locale: Locale): string {
  return value
    .split(" · ")
    .map((part) => {
      const tower = /^([1-4]) 级塔$/u.exec(part);
      if (tower)
        return translate(locale, "{tier} 级防御塔", { tier: tower[1] });
      const level = /^等级 (.+)$/u.exec(part);
      if (level)
        return translate(locale, "等级 {level}", {
          level: translate(locale, level[1]),
        });
      return translate(locale, part);
    })
    .join(" · ");
}
export function campGroupLabel(value: string, locale: Locale): string {
  const mixed = /^混合进化 · (\d+)\/3 已升级$/u.exec(value);
  return mixed
    ? translate(locale, "混合进化 · {count}/3 已升级", { count: mixed[1] })
    : translate(locale, value);
}
