\set ON_ERROR_STOP on

-- Checked migrations 0001-0006 name these roles directly. They are NOLOGIN
-- grant templates only; migration 0007 reconciles their ACLs onto the
-- database-local login roles and removes the template ACLs.
CREATE ROLE medota2_worker NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE medota2_web NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;

CREATE ROLE medota2_dev_control_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE medota2_test_control_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE medota2_local_control_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;

CREATE ROLE medota2_dev_migration NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE medota2_dev_worker NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE medota2_dev_web NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;

CREATE ROLE medota2_test_migration NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE medota2_test_worker NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE medota2_test_web NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;

CREATE ROLE medota2_local_migration NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE medota2_local_worker NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE medota2_local_web NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;

ALTER DATABASE medota2 OWNER TO medota2_dev_migration;
REVOKE CONNECT, TEMPORARY ON DATABASE medota2 FROM PUBLIC, medota2_worker, medota2_web;
GRANT CONNECT, TEMPORARY ON DATABASE medota2 TO medota2_dev_migration;
GRANT CONNECT ON DATABASE medota2 TO medota2_dev_worker, medota2_dev_web;

CREATE DATABASE medota2_test OWNER medota2_test_migration;
REVOKE CONNECT, TEMPORARY ON DATABASE medota2_test FROM PUBLIC, medota2_worker, medota2_web;
GRANT CONNECT, TEMPORARY ON DATABASE medota2_test TO medota2_test_migration;
GRANT CONNECT ON DATABASE medota2_test TO medota2_test_worker, medota2_test_web;

\connect medota2
CREATE DATABASE medota2_local OWNER medota2_local_migration;
REVOKE CONNECT, TEMPORARY ON DATABASE medota2_local FROM PUBLIC, medota2_worker, medota2_web;
GRANT CONNECT, TEMPORARY ON DATABASE medota2_local TO medota2_local_migration;
GRANT CONNECT ON DATABASE medota2_local TO medota2_local_worker, medota2_local_web;

\connect postgres
REVOKE CONNECT, TEMPORARY ON DATABASE postgres FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE template1 FROM PUBLIC;
