// Product search vocabulary, independent of Valve's versioned gameplay data.
// Ambiguous aliases intentionally match every associated hero (e.g. ES, SK).
export const HERO_ALIASES: Record<string, readonly string[]> = {
  antimage: ["敌法", "AM", "Magina", "玛吉纳", "大敌法"],
  axe: ["斧头", "Mogul Khan"],
  bane: ["祸乱", "Bane Elemental", "Atropos"],
  bloodseeker: ["血魔", "BS", "Strygwyr"],
  crystal_maiden: ["冰女", "CM", "Rylai", "莉莱"],
  drow_ranger: ["小黑", "黑弓", "DR", "Traxex"],
  earthshaker: ["小牛", "牛头", "神牛", "ES", "Raigor"],
  juggernaut: ["剑圣", "Jugg", "Yurnero", "尤涅若"],
  mirana: ["白虎", "月女", "POTM", "Pom"],
  morphling: ["水人", "Morph"],
  nevermore: ["影魔", "SF", "Shadow Fiend"],
  phantom_lancer: ["猴子", "幻影长矛手", "PL", "Azwraith"],
  puck: ["精灵龙", "帕克", "Faerie Dragon"],
  pudge: ["屠夫", "胖子", "Butcher"],
  razor: ["电魂", "电棍", "Lightning Revenant"],
  sand_king: ["沙王", "SK", "Crixalis"],
  storm_spirit: ["蓝猫", "风暴之灵", "SS", "Storm", "Raijin"],
  sven: ["流浪剑客", "流浪", "斯温", "Rogue Knight"],
  tiny: ["小小", "山岭巨人", "Stone Giant"],
  vengefulspirit: ["VS", "复仇", "Venge", "Vengeful Spirit"],
  windrunner: ["风行", "WR", "Windranger", "Lyralei"],
  zuus: ["宙斯", "Zeus"],
  kunkka: ["船长", "海军上将", "Admiral"],
  lina: ["火女", "秀逗魔导士", "Slayer"],
  lich: ["巫妖", "Kelthuzad"],
  lion: ["莱恩", "恶魔巫师", "Demon Witch"],
  shadow_shaman: ["小Y", "暗影萨满", "SS", "Rhasta"],
  slardar: ["大鱼", "大鱼人", "SG", "Slithereen Guard"],
  tidehunter: ["潮汐", "Tide", "TH", "Leviathan"],
  witch_doctor: ["巫医", "WD", "Voljin"],
  riki: ["隐刺", "力丸", "SA", "Stealth Assassin"],
  enigma: ["谜团", "大谜团"],
  tinker: ["修补匠", "TK", "Boush"],
  sniper: ["火枪", "矮人火枪手", "Kardel"],
  necrolyte: ["死灵法", "死灵法师", "NEC", "Necrophos", "Rotundjere"],
  warlock: ["术士", "WL", "Demnok Lannik"],
  beastmaster: ["兽王", "BM", "Rexxar"],
  queenofpain: ["女王", "痛苦女王", "QOP", "Queen of Pain", "Akasha"],
  venomancer: ["剧毒", "Veno", "Lesale"],
  faceless_void: ["虚空", "假面", "FV", "Void", "Darkterror"],
  skeleton_king: [
    "骷髅王",
    "冥魂大帝",
    "大帝",
    "WK",
    "SK",
    "Wraith King",
    "Leoric",
  ],
  death_prophet: ["死亡先知", "DP", "Krobelus"],
  phantom_assassin: ["幻刺", "PA", "Mortred"],
  pugna: ["骨法", "遗忘法师", "Oblivion"],
  templar_assassin: ["圣堂", "TA", "Lanaya"],
  viper: ["毒龙", "冥界亚龙", "Netherdrake"],
  luna: ["月骑", "Moon Rider"],
  dragon_knight: ["龙骑", "DK", "Davion"],
  dazzle: ["暗牧", "戴泽", "Shadow Priest"],
  rattletrap: ["发条", "发条地精", "Clock", "Clockwerk"],
  leshrac: ["老鹿", "拉席克", "Lesh", "Tormented Soul"],
  furion: ["先知", "NP", "Nature's Prophet"],
  life_stealer: ["小狗", "噬魂鬼", "LS", "Lifestealer", "Naix"],
  dark_seer: ["兔子", "黑贤", "DS", "Ishkafel"],
  clinkz: ["小骷髅", "骨弓", "骷髅射手", "Bone Fletcher"],
  omniknight: ["全能", "全能骑士", "Omni", "Purist"],
  enchantress: ["小鹿", "魅惑魔女", "Ench", "Aiushtha"],
  huskar: ["神灵", "哈斯卡", "神灵武士", "Husk", "Sacred Warrior"],
  night_stalker: ["夜魔", "NS", "Balanar"],
  broodmother: ["蜘蛛", "育母蜘蛛", "Brood", "BM"],
  bounty_hunter: ["赏金", "BH", "Gondar"],
  weaver: ["蚂蚁", "编织者", "Nerubian Weaver"],
  jakiro: ["双头龙", "THD", "Twin Head Dragon"],
  batrider: ["蝙蝠", "Bat"],
  chen: ["陈", "圣骑士", "Holy Knight"],
  spectre: ["幽鬼", "SPE", "Spec", "Mercurial"],
  ancient_apparition: ["冰魂", "AA", "Kaldr"],
  doom_bringer: ["末日", "末日使者", "Doom", "Lucifer"],
  ursa: ["拍拍", "拍拍熊", "熊战士", "Ursa Warrior"],
  spirit_breaker: ["白牛", "SB", "Barathrum"],
  gyrocopter: ["飞机", "矮人直升机", "Gyro"],
  alchemist: ["炼金", "炼金术士", "Alch", "GA"],
  invoker: ["卡尔", "祈求者", "Kael", "Carl"],
  silencer: ["沉默", "沉默术士", "Nortrom"],
  obsidian_destroyer: [
    "黑鸟",
    "殁境神蚀者",
    "OD",
    "Outworld Destroyer",
    "Outworld Devourer",
    "Outworld Demolisher",
  ],
  lycan: ["狼人", "Lycanthrope", "Banehallow"],
  brewmaster: ["酒仙", "熊猫", "Brew", "Panda", "Mangix"],
  shadow_demon: ["毒狗", "暗影恶魔", "SD", "Eredar"],
  lone_druid: ["德鲁伊", "熊德", "LD", "Syllabear"],
  chaos_knight: ["混沌", "混沌骑士", "CK"],
  meepo: ["米波", "地卜师", "狗头", "Geomancer"],
  treant: ["大树", "树精", "树精卫士", "Treant Protector", "Rooftrellen"],
  ogre_magi: ["蓝胖", "食人魔", "蓝胖子", "Ogre", "OM"],
  undying: ["尸王", "不朽尸王", "Dirge"],
  rubick: ["拉比克", "大魔导师", "Rubik", "Grand Magus"],
  disruptor: ["萨尔", "干扰者", "Thrall"],
  nyx_assassin: ["小强", "司夜刺客", "NA", "Nerubian Assassin"],
  naga_siren: ["小娜迦", "娜迦", "Naga", "Slithice"],
  keeper_of_the_light: ["光法", "光之守卫", "KOTL", "Ezalor"],
  wisp: ["小精灵", "IO", "精灵守卫"],
  visage: ["死灵龙", "维萨吉", "Necrolic"],
  slark: ["小鱼", "小鱼人", "鱼人夜行者"],
  medusa: ["大娜迦", "美杜莎", "一姐", "Dusa", "Gorgon"],
  troll_warlord: ["巨魔", "巨魔战将", "TW", "Troll"],
  centaur: ["人马", "半人马", "人马战行者", "Centaur Warrunner", "Bradwarden"],
  magnataur: ["猛犸", "马格纳斯", "Magnus", "Mag"],
  shredder: ["伐木机", "Timbersaw", "Timber", "Rizzrack"],
  bristleback: ["钢背", "钢背兽", "BB", "Rigwarl"],
  tusk: ["海民", "巨牙海民", "Ymir"],
  skywrath_mage: ["天怒", "天怒法师", "Sky", "SM"],
  abaddon: ["亚巴顿", "死骑", "地狱领主", "Aba", "Lord of Avernus"],
  elder_titan: ["大牛", "上古巨神", "ET", "牛头人酋长"],
  legion_commander: ["军团", "军团指挥官", "LC", "Tresdin"],
  ember_spirit: ["火猫", "灰烬之灵", "Ember", "ES", "Xin"],
  earth_spirit: ["土猫", "大地之灵", "ES", "Kaolin"],
  terrorblade: ["恐怖利刃", "魂守", "TB", "Soul Keeper"],
  phoenix: ["凤凰", "火鸟"],
  techies: ["炸弹人", "炸弹", "地精工程师", "Goblin Techies"],
  oracle: ["神谕", "神谕者"],
  winter_wyvern: ["冰龙", "寒冬飞龙", "WW"],
  arc_warden: ["电狗", "天穹守望者", "AW", "Zet"],
  abyssal_underlord: ["大屁股", "孽主", "Underlord", "Pit Lord", "Atrophy"],
  monkey_king: ["大圣", "齐天大圣", "MK", "Sun Wukong"],
  pangolier: ["滚滚", "石鳞剑士", "Pango"],
  dark_willow: ["小仙女", "邪影芳灵", "DW", "Mireska"],
  grimstroke: ["墨客", "天涯墨客", "Grim"],
  mars: ["马尔斯", "战神"],
  void_spirit: ["紫猫", "虚无之灵", "Void Spirit", "VS", "Inai"],
  snapfire: ["老奶奶", "电炎绝手", "Snap", "Beatrix"],
  hoodwink: ["松鼠", "森海飞霞", "Hood"],
  dawnbreaker: ["锤妹", "破晓辰星", "DB", "Dawn", "Valora"],
  marci: ["玛西", "哑巴"],
  primal_beast: ["大兽", "兽", "PB", "Primal"],
  muerta: ["琼英碧灵", "奶绿", "亡灵枪手"],
  ringmaster: ["百戏大王", "马戏团", "Ring Master"],
  kez: ["凯", "鸟人", "武士鸟"],
};

export const ABILITY_ALIASES: Record<string, readonly string[]> = {
  antimage_blink: ["敌法闪", "敌法跳", "闪现", "Blink"],
  queenofpain_blink: ["女王闪", "女王跳", "闪现"],
  antimage_mana_break: ["削蓝", "消蓝", "法力损毁"],
  antimage_mana_void: ["蓝爆", "法力虚空", "Mana Bomb"],
  axe_culling_blade: ["淘汰", "斩杀", "斩杀斧", "Dunk"],
  pudge_meat_hook: ["钩", "钩子", "肉钩", "Hook"],
  pudge_dismember: ["咬", "肢解", "Bite"],
  mirana_arrow: ["月神箭", "白虎箭", "神箭", "Arrow"],
  nevermore_shadowraze1: ["影压", "近炮", "压炮", "Raze"],
  nevermore_shadowraze2: ["影压", "中炮", "压炮", "Raze"],
  nevermore_shadowraze3: ["影压", "远炮", "压炮", "Raze"],
  nevermore_requiem: ["魂之挽歌", "摇大", "SF Ult"],
  invoker_sun_strike: ["天火", "Sunstrike"],
  invoker_tornado: ["吹风", "龙卷风"],
  invoker_emp: ["磁暴", "抽蓝"],
  invoker_chaos_meteor: ["陨石", "Meteor"],
  invoker_deafening_blast: ["推波", "超震声波"],
  faceless_void_chronosphere: ["罩子", "大罩", "Chrono"],
  enigma_black_hole: ["黑洞", "BH"],
  earthshaker_echo_slam: ["回音击", "跳大", "Echo"],
  magnataur_reverse_polarity: ["两极反转", "猛犸大", "RP"],
  juggernaut_omni_slash: ["无敌斩", "Omnislash"],
  juggernaut_blade_fury: ["剑刃风暴", "转", "Spin"],
  tidehunter_ravage: ["毁灭", "潮汐大"],
  kunkka_ghostship: ["幽灵船", "船", "Boat"],
  kunkka_torrent: ["洪流", "水"],
  kunkka_x_marks_the_spot: ["标记", "X Mark"],
  lina_laguna_blade: ["神灭斩", "Laguna"],
  lion_finger_of_death: ["死亡一指", "一指", "Finger"],
  zuus_thundergods_wrath: ["雷神之怒", "全屏雷", "Zeus Ult"],
  storm_spirit_ball_lightning: ["球状闪电", "飞", "Ball"],
  phoenix_supernova: ["超新星", "变蛋", "凤凰蛋", "Egg"],
  winter_wyvern_winters_curse: ["寒冬诅咒", "冰龙大", "Curse"],
  disruptor_static_storm: ["静态风暴", "框大"],
  void_spirit_aether_remnant: ["残阴", "紫猫拉"],
  tiny_avalanche: ["山崩", "VT", "Avalanche"],
  tiny_toss: ["投掷", "扔", "VT", "Toss"],
};
