/** Explicit summon/effect relationships; these are related skill icons, never portraits. */
export const UNIT_ABILITY_ICONS: Record<string, string> = {
  npc_dota_treant_eyes: "treant_eyes_in_the_forest",
  npc_dota_unit_underlord_portal: "abyssal_underlord_dark_portal",
  npc_dota_unit_templar_gate: "templar_assassin_trap_teleport",
  npc_dota_muerta_ofrenda: "muerta_ofrenda",
  npc_dota_tinker_turret1: "tinker_deploy_turrets",
  npc_dota_tinker_turret2: "tinker_deploy_turrets",
  npc_dota_tinker_turret3: "tinker_deploy_turrets",
  npc_dota_tinker_turret4: "tinker_deploy_turrets",
  npc_dota_rattletrap_rocket: "rattletrap_rocket_flare",
  npc_dota_stormspirit_remnant: "storm_spirit_static_remnant",
  npc_dota_ember_spirit_remnant: "ember_spirit_fire_remnant",
  npc_dota_slark_visual: "slark_shadow_dance",
  npc_dota_plasma_field: "razor_plasma_field",
  npc_dota_metamorphosis_fear: "terrorblade_terror_wave",
  npc_dota_wisp_spirit: "wisp_spirits",
  npc_dota_beastmaster_axe: "beastmaster_wild_axes",
  npc_dota_troll_warlord_axe: "troll_warlord_whirling_axes_ranged",
  npc_dota_phantom_assassin_ground_dagger: "phantom_assassin_stifling_dagger",
  dota_death_prophet_exorcism_spirit: "death_prophet_exorcism",
  npc_dota_dark_willow_creature: "dark_willow_bedlam",
  npc_dota_aether_remnant: "void_spirit_aether_remnant",
  npc_dota_centaur_cart: "centaur_work_horse",
  npc_dota_meepo_megameepo_frame: "meepo_megameepo",
  npc_dota_ringmaster_wheel: "ringmaster_wheel",
  npc_dota_largo_frogling: "largo_frogstomp",
  aghsfort_mars_bulwark_soldier: "mars_bulwark",
};
